FROM node:18-alpine as builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm ci --prefer-offline --no-audit

COPY frontend/ .

RUN npm run build

# Production
FROM node:18-alpine

WORKDIR /app

COPY frontend/package.json ./

RUN npm install --only=production express

COPY --from=builder /app/dist ./dist

COPY frontend/server.js .

EXPOSE 3000

CMD ["node", "server.js"]
