# Generated by Django 5.2.8 on 2025-11-17 08:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Descuento/Retención')),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], max_length=20)),
                ('category', models.CharField(choices=[('discount', 'Descuento'), ('retention', 'Retención'), ('deduction', 'Deducción')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='¿Es Obligatorio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descuento/Retención',
                'verbose_name_plural': 'Descuentos/Retenciones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Servicio')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Base')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Comisión (%)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código del Servicio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Licencia')),
                ('specialization', models.CharField(max_length=100, verbose_name='Especialización')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=20)),
                ('default_commission_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Comisión por Defecto (%)')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Cuenta Bancaria')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Banco')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('patient_id', models.CharField(blank=True, max_length=50, verbose_name='Cédula del Paciente')),
                ('date', models.DateTimeField(verbose_name='Fecha de Atención')),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Cobrado')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Comisión (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attentions', to='payments.professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attentions', to='payments.service')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='Fecha Inicio Período')),
                ('period_end', models.DateField(verbose_name='Fecha Fin Período')),
                ('total_attended', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Atenciones')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Comisión')),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Descuentos')),
                ('total_retentions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Retenciones')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Neto a Pagar')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('calculated', 'Calculada'), ('approved', 'Aprobada'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_created', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='payments.professional')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SettlementDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.discount')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_applied', to='payments.settlement')),
            ],
            options={
                'verbose_name': 'Descuento en Liquidación',
                'verbose_name_plural': 'Descuentos en Liquidación',
            },
        ),
        migrations.CreateModel(
            name='SettlementLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('service_code', models.CharField(blank=True, max_length=50)),
                ('attendance_date', models.DateField()),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.attention')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.settlement')),
            ],
            options={
                'verbose_name': 'Detalle de Liquidación',
                'verbose_name_plural': 'Detalles de Liquidación',
            },
        ),
        migrations.AddIndex(
            model_name='attention',
            index=models.Index(fields=['professional', '-date'], name='payments_at_profess_58fd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='attention',
            index=models.Index(fields=['status', '-date'], name='payments_at_status_c17baa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('professional', 'period_start', 'period_end')},
        ),
    ]
