# Generated by Django 5.2.8 on 2025-11-17 09:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Aseguradora')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto Fijo')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor del Descuento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Descuento por Aseguradora',
                'verbose_name_plural': 'Descuentos por Aseguradora',
                'ordering': ['insurance_name'],
            },
        ),
        migrations.AddField(
            model_name='attention',
            name='health_insurance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Aseguradora de Salud'),
        ),
        migrations.AddField(
            model_name='attention',
            name='insurance_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento por Aseguradora (%)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Creado'), ('update', 'Actualizado'), ('delete', 'Eliminado'), ('status_change', 'Cambio de Estado'), ('payment', 'Pago Registrado'), ('settlement_generated', 'Liquidación Generada')], max_length=30)),
                ('model_name', models.CharField(choices=[('User', 'Usuario'), ('Professional', 'Profesional'), ('Service', 'Servicio'), ('Attention', 'Atención'), ('Settlement', 'Liquidación'), ('Discount', 'Descuento')], max_length=50)),
                ('object_id', models.CharField(max_length=200, verbose_name='ID del Objeto')),
                ('object_description', models.CharField(blank=True, max_length=500, verbose_name='Descripción del Objeto')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Cambios (JSON)')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Valores Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_au_user_id_733221_idx'), models.Index(fields=['model_name', '-created_at'], name='payments_au_model_n_1c1fd1_idx'), models.Index(fields=['action', '-created_at'], name='payments_au_action_343b77_idx')],
            },
        ),
    ]
