# Generated by Django 5.2.8 on 2025-11-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_settlement_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Licencia'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialización'),
        ),
    ]
