# Generated by Django 5.2.8 on 2025-11-18 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_professional_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlementlineitem',
            name='attention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.attention'),
        ),
    ]
