# Generated by Django 5.2.8 on 2025-11-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_settlementlineitem_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attentions', to='payments.professional'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payments.professional'),
        ),
    ]
